"use client";

import { useState } from "react";
import { ChevronDown, Download, Image, Layers3, Minus, Plus, Redo2, Save, Square, Text, Undo2, Upload, ZoomIn } from "lucide-react";

export default function Editor() {
  const [zoom, setZoom] = useState(70);
  const [selected, setSelected] = useState("Heading");
  return <div className="flex h-screen flex-col overflow-hidden bg-[#f3f3f1] text-[#161616]">
    <header className="flex h-14 shrink-0 items-center justify-between border-b border-black/10 bg-white px-4">
      <div className="flex items-center gap-4"><a href="/" className="text-xl font-black tracking-[-.05em]">veyra.</a><div className="h-5 w-px bg-black/10"/><button className="flex items-center gap-1 text-sm font-semibold">Untitled design <ChevronDown size={15}/></button></div>
      <div className="flex items-center gap-2"><span className="hidden text-xs text-black/40 sm:inline-flex"><Save size={14}/> Saved locally</span><button className="rounded-lg border border-black/10 p-2 hover:bg-black/5"><Undo2 size={16}/></button><button className="rounded-lg border border-black/10 p-2 hover:bg-black/5"><Redo2 size={16}/></button><button className="flex items-center gap-2 rounded-lg bg-[#6d5dfc] px-4 py-2 text-sm font-bold text-white"><Download size={15}/> Export</button></div>
    </header>
    <div className="flex min-h-0 flex-1">
      <aside className="w-[76px] shrink-0 border-r border-black/10 bg-white py-3"><div className="flex flex-col items-center gap-2">{[[Text,"Text"],[Image,"Media"],[Square,"Shapes"],[Layers3,"Layers"],[Upload,"Uploads"]].map(([Icon,label])=>{const I=Icon as typeof Text; return <button key={label as string} className="flex w-16 flex-col items-center gap-1 rounded-xl py-2 text-[10px] font-semibold text-black/55 hover:bg-[#f1efff] hover:text-[#6d5dfc]"><I size={20}/>{label as string}</button>})}</div></aside>
      <section className="flex min-w-0 flex-1 flex-col">
        <div className="flex h-12 shrink-0 items-center justify-center gap-1 border-b border-black/10 bg-white/70"><button className="rounded-md p-2 hover:bg-black/5"><Undo2 size={15}/></button><button className="rounded-md p-2 hover:bg-black/5"><Redo2 size={15}/></button><div className="mx-2 h-5 w-px bg-black/10"/><button className="rounded-md px-3 py-1.5 text-xs font-semibold hover:bg-black/5">Position</button><button className="rounded-md px-3 py-1.5 text-xs font-semibold hover:bg-black/5">Animate</button><button className="rounded-md px-3 py-1.5 text-xs font-semibold hover:bg-black/5">Effects</button></div>
        <div className="relative flex flex-1 items-center justify-center overflow-auto bg-[#e9e9e7] p-12"><div className="relative aspect-[16/9] w-[min(780px,80vw)] bg-white shadow-[0_12px_45px_rgba(0,0,0,.15)]"><button onClick={()=>setSelected("Heading")} className={`absolute left-[11%] top-[20%] text-left text-6xl font-black tracking-[-.06em] outline-none ${selected==="Heading"?"ring-2 ring-[#6d5dfc] ring-offset-4":""}`}>Create<br/><span className="text-[#6d5dfc]">something.</span></button><button onClick={()=>setSelected("Subtitle")} className={`absolute bottom-[17%] left-[11%] text-left text-lg text-black/50 ${selected==="Subtitle"?"ring-2 ring-[#6d5dfc] ring-offset-4":""}`}>A canvas for your next idea.</button><div className="absolute right-[11%] top-[18%] h-44 w-44 rounded-[2.5rem] bg-[#f0edff]"/><div className="absolute right-[18%] top-[28%] h-24 w-24 rounded-3xl bg-[#6d5dfc] shadow-xl shadow-[#6d5dfc]/25"/></div></div>
        <div className="flex h-11 shrink-0 items-center justify-center gap-3 border-t border-black/10 bg-white"><button onClick={()=>setZoom(Math.max(30,zoom-10))}><Minus size={14}/></button><span className="w-12 text-center text-xs font-semibold">{zoom}%</span><button onClick={()=>setZoom(Math.min(150,zoom+10))}><Plus size={14}/></button><ZoomIn size={15} className="ml-2 text-black/40"/></div>
      </section>
      <aside className="hidden w-64 shrink-0 border-l border-black/10 bg-white lg:block"><div className="border-b border-black/10 p-4"><p className="text-xs font-bold uppercase tracking-wider text-black/40">Inspector</p><p className="mt-1 font-bold">{selected}</p></div><div className="space-y-5 p-4"><div><label className="text-xs font-semibold text-black/50">Position</label><div className="mt-2 grid grid-cols-2 gap-2"><input className="rounded-lg border border-black/10 px-3 py-2 text-sm" value="120" readOnly/><input className="rounded-lg border border-black/10 px-3 py-2 text-sm" value="96" readOnly/></div></div><div><label className="text-xs font-semibold text-black/50">Size</label><div className="mt-2 grid grid-cols-2 gap-2"><input className="rounded-lg border border-black/10 px-3 py-2 text-sm" value="640" readOnly/><input className="rounded-lg border border-black/10 px-3 py-2 text-sm" value="180" readOnly/></div></div><div><label className="text-xs font-semibold text-black/50">Opacity</label><input type="range" className="mt-3 w-full" defaultValue="100"/></div></div></aside>
    </div>
  </div>;
}
